const index = require('../models/index');

let Blog = index.models.Blog;
let blog = new Blog();
blog.collection.remove({});
let blogs = [
	{
		blogTitle:"Health in a snack",
		blogBody:"Fusce quis enim vitae velit maximus volutpat. Nam eget tincidunt mauris. Cras varius elementum justo nec scelerisque. Curabitur hendrerit ex nec augue pulvinar, in ultricies augue condimentum. Duis ligula libero, ornare a quam at, convallis aliquet elit. Vestibulum consequat nisi orci, a iaculis tortor suscipit id. Aliquam scelerisque lacus in velit imperdiet tincidunt. Praesent tristique, nisi viverra luctus malesuada, nulla urna facilisis felis, tincidunt tincidunt ipsum dolor ac nulla. Aenean elementum tortor in est faucibus, vitae rhoncus turpis scelerisque. Integer rhoncus vehicula ex eget sodales. Sed iaculis mi pulvinar, accumsan urna ut, mollis quam. Nulla id sodales elit, non finibus dui. Integer non lectus bibendum, pulvinar libero sed, ullamcorper arcu. Cras efficitur mi ut dolor condimentum iaculis. Proin hendrerit dolor nec lobortis tempus. Quisque eget mi non magna fermentum vehicula non at nulla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies tincidunt nisl, vitae aliquet ante varius sit amet. Duis consequat sit amet odio at scelerisque. Cras maximus urna condimentum tellus facilisis, sit amet vulputate eros tempus. In hac habitasse platea dictumst. Sed vel vehicula turpis. Cras magna diam, vulputate nec elit sed, vehicula convallis mauris. Vivamus aliquet dignissim molestie. Aenean vitae viverra quam.",
		date: Date()
	},
	{
		blogTitle: "Green Tea benifits",
		blogBody:"Fusce quis enim vitae velit maximus volutpat. Nam eget tincidunt mauris. Cras varius elementum justo nec scelerisque. Curabitur hendrerit ex nec augue pulvinar, in ultricies augue condimentum. Duis ligula libero, ornare a quam at, convallis aliquet elit. Vestibulum consequat nisi orci, a iaculis tortor suscipit id. Aliquam scelerisque lacus in velit imperdiet tincidunt. Praesent tristique, nisi viverra luctus malesuada, nulla urna facilisis felis, tincidunt tincidunt ipsum dolor ac nulla. Aenean elementum tortor in est faucibus, vitae rhoncus turpis scelerisque. Integer rhoncus vehicula ex eget sodales. Sed iaculis mi pulvinar, accumsan urna ut, mollis quam. Nulla id sodales elit, non finibus dui. Integer non lectus bibendum, pulvinar libero sed, ullamcorper arcu. Cras efficitur mi ut dolor condimentum iaculis. Proin hendrerit dolor nec lobortis tempus. Quisque eget mi non magna fermentum vehicula non at nulla. Aliquam eros dui, euismod id efficitur non, iaculis eu metus. Vestibulum accumsan, risus ac interdum vulputate, diam enim tempus odio, at hendrerit sapien magna nec massa. Duis posuere massa non nisi posuere, id aliquet diam mollis. Nam eget felis ac libero lacinia suscipit. Maecenas sollicitudin massa id orci semper feugiat. Sed id dapibus turpis. Quisque eleifend, lacus eu ornare tincidunt, purus metus porttitor dolor, et cursus neque tortor a dolor."
	},
	{
		blogTitle:"Vitamin C",
		blogBody:"Fusce quis enim vitae velit maximus volutpat. Nam eget tincidunt mauris. Cras varius elementum justo nec scelerisque. Curabitur hendrerit ex nec augue pulvinar, in ultricies augue condimentum. Duis ligula libero, ornare a quam at, convallis aliquet elit. Vestibulum consequat nisi orci, a iaculis tortor suscipit id. Aliquam scelerisque lacus in velit imperdiet tincidunt. Praesent tristique, nisi viverra luctus malesuada, nulla urna facilisis felis, tincidunt tincidunt ipsum dolor ac nulla. Aenean elementum tortor in est faucibus, vitae rhoncus turpis scelerisque. Integer rhoncus vehicula ex eget sodales. Sed iaculis mi pulvinar, accumsan urna ut, mollis quam. Nulla id sodales elit, non finibus dui. Integer non lectus bibendum, pulvinar libero sed, ullamcorper arcu. Cras efficitur mi ut dolor condimentum iaculis. Proin hendrerit dolor nec lobortis tempus. Quisque eget mi non magna fermentum vehicula non at nulla. Aliquam eros dui, euismod id efficitur non, iaculis eu metus. Vestibulum accumsan, risus ac interdum vulputate, diam enim tempus odio, at hendrerit sapien magna nec massa. Duis posuere massa non nisi posuere, id aliquet diam mollis. Nam eget felis ac libero lacinia suscipit. Maecenas sollicitudin massa id orci semper feugiat. Sed id dapibus turpis. Quisque eleifend, lacus eu ornare tincidunt, purus metus porttitor dolor, et cursus neque tortor a dolor.",
		date: Date()
	},
	{
		blogTitle:"Natural immunity",
		blogBody:"Fusce quis enim vitae velit maximus volutpat. Nam eget tincidunt mauris. Cras varius elementum justo nec scelerisque. Curabitur hendrerit ex nec augue pulvinar, in ultricies augue condimentum. Duis ligula libero, ornare a quam at, convallis aliquet elit. Vestibulum consequat nisi orci, a iaculis tortor suscipit id. Aliquam scelerisque lacus in velit imperdiet tincidunt. Praesent tristique, nisi viverra luctus malesuada, nulla urna facilisis felis, tincidunt tincidunt ipsum dolor ac nulla. Aenean elementum tortor in est faucibus, vitae rhoncus turpis scelerisque. Integer rhoncus vehicula ex eget sodales. Sed iaculis mi pulvinar, accumsan urna ut, mollis quam. Nulla id sodales elit, non finibus dui. Integer non lectus bibendum, pulvinar libero sed, ullamcorper arcu. Cras efficitur mi ut dolor condimentum iaculis. Proin hendrerit dolor nec lobortis tempus. Quisque eget mi non magna fermentum vehicula non at nulla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies tincidunt nisl, vitae aliquet ante varius sit amet. Duis consequat sit amet odio at scelerisque. Cras maximus urna condimentum tellus facilisis, sit amet vulputate eros tempus. In hac habitasse platea dictumst. Sed vel vehicula turpis. Cras magna diam, vulputate nec elit sed, vehicula convallis mauris. Vivamus aliquet dignissim molestie.",
		date: Date()
	},
	{
		blogTitle:"B12 powers",
		blogBody:"Nunc tincidunt molestie vehicula. Aliquam et eleifend est, vitae sagittis neque. Etiam ut justo fringilla, dignissim tellus et, suscipit tortor. Maecenas in ligula magna. Ut vitae ipsum nulla. Cras vehicula mauris in libero tempus laoreet. Cras porta metus lectus, a consequat ligula convallis eu. Aliquam finibus felis vitae ligula ornare, sed vehicula quam cursus. Nam lorem leo, placerat eget elementum quis, mattis ac diam. Vivamus cursus sollicitudin maximus. Maecenas vitae leo massa. Quisque eu mattis lacus, ac fermentum mi. Etiam interdum, magna quis feugiat ullamcorper, nisl lectus viverra felis, vitae fringilla augue neque vestibulum sem. Praesent pretium nisl et ligula consequat suscipit. Donec egestas mollis nibh, placerat egestas leo tincidunt id. Maecenas pulvinar fringilla volutpat. Nunc ac fermentum felis, eu convallis ante. Maecenas mollis dapibus urna, nec malesuada ex mattis ac. Quisque facilisis mauris interdum orci dictum mollis. Curabitur id quam id ipsum sodales consequat. Ut finibus metus sed risus commodo, ullamcorper viverra dolor condimentum. Mauris turpis diam, iaculis sed imperdiet in, viverra id justo. Maecenas consequat vitae erat eu egestas. Vivamus sit amet sagittis lectus. Phasellus gravida arcu arcu, in volutpat dui imperdiet eget. Donec rhoncus leo ac nulla hendrerit sagittis at quis nulla.",
		date: Date()
	},
];
Blog.create(blogs,() => process.exit(0))
