const index = require('../models/index');

let Blog = index.models.Blog;
let blog = new Blog();
blog.collection.remove({});
let blogs = [
	{
		blogTitle:"Hidden Dangers of Heartburn Drugs By Tracy Garfield",
		blogBody:"In profoundly troubling studies published in 2015-2016, acid reducing drugs called proton pump inhibitors, or PPIs, were associated with an increased risk of dementia. One of these studies found cognitive impairment in response to short-term use of drugs sold under the names Prevacid®, Nexium®, Protonix®, AcipHex®, and Prilosec®.2 People age 75 and older who use proton pump inhibitors have a 44% greater risk of developing dementia, including Alzheimer’s. As many as 70% of people taking proton pump inhibitors don’t require them. Thousands of cases of dementia may have been avoided if people weren’t overusing these drugs. In this article we will examine how proton pump inhibitors pose a hidden long-term threat to our brains. We’ll discuss natural options that can help alleviate heartburn symptoms without increasing dementia and other health risks such as bone fractures, kidney failure, and stroke. Proton Pump Inhibitors Increase Dementia Risk The recent studies showing an association between proton pump inhibitors and increased risk of dementia are frightening.1-3 These drugs are some of the most widely used in America, and their use among the elderly is on the rise. Proton pump inhibitors are most often used to fight heartburn, gastroesophageal reflux (GERD), and other painful disorders of the upper digestive tract. They are available over the counter and by prescription. The most recent of the new studies appeared online in the Journal of the American Medical Association Neurology in February 2016.",
		date: Date().toString()
	},
	{
		blogTitle: "A Thumb Up Book Review. Reviewed By Katherine Czapp",
		blogBody:"The first thing to understand about The High Blood Pressure Hoax is that author Sherry Rogers considers hypertension itself to be no hoax at all, but a very real and serious symptom of vascular dysfunction that can be associated with numerous illnesses such as diabetes, heart disease and Alzheimer’s. As a marker of something out of balance in the body, high blood pressure is not to be ignored, Dr. Rogers emphasizes, and in fact she completely endorses, the recently recalibrated “normal” blood pressure reading of 120/70 along with the new symptom designation of “prehypertension”–also known as the not-long-ago “normal” measurement of 140/90. On this point of raising the alarm with regard to blood pressure readings, Dr. Rogers temporarily parts company with a number of thoughtful physicians, both old school and of alternative persuasions. Dr. William Campbell Douglass, for example, provides good arguments for leaving moderate hypertension alone, noting that in the absence of other symptoms, untreated hypertension may be of little concern, while treatment with the known classes of antihypertensive drugs inevitably results in serious health-damaging side effects that tend to worsen the longer treatment continues. Even with drug management, fully half of those with high blood pressure still cannot control it, all the while feeling worse while on the drugs. Dr. Tom Cowan, in his book The Fourfold Path to Healing, outlines an approach to normalizing blood pressure through diet, supplements and movement plus meditation.",
		date: Date()
	},
	{
		blogTitle:"Cortisol & DHEA: The Major Hormone Balance By Michael Mcevoy ",
		blogBody:"The cortisol to DHEA ratio is believed to be so important to your health, that numerous functions in the body are deficient without it. Cortisol and DHEA are both powerful adrenal hormones that have a variety of physiological functions. Cortisol and DHEA are steroid hormones, both synthesized from pregnenelone, the master steroid hormone, which is derived from cholesterol. In many ways, the Cortisol to DHEA ratio modulates biological energy output, and their effects are felt at the cellular level all over the body. Functions of Cortisol & DHEA Cortisol is a primary stress hormone produced by the adrenals, and is also a potent anti-inflammatory hormone. Cortisol's action can suppress immune function. Another of its primary functions is to raise blood sugar through gluconeogenesis. High amounts of glucocorticoids can suppress thyroid function, chiefly the inhibition of the conversion of T4 into the active T3. CRH (cortico-tropin releasing hormone), which is a hypothalamus precursor to cortisol can inhibit thyroid function as well, suppressing TSH. DHEA (dehydroepiandrosterone) is called an androgenic hormone. It is a precursor for testosterone and the estrogens. DHEA antagonizes the effects of cortisol. DHEA is a very powerful anti-aging hormone. Low levels of DHEA are found among those with Cancer, CVD, Alzheimer's, Diabetes, Depression, Hypothyroidism and Adrenal Fatigue. Since cortisol and DHEA have opposing effects, they should be viewed together as a ratio. Like with every major control system in the body, cortisol and DHEA work through their alternating, dualistic balance.",
		date: Date()
	},
	{
		blogTitle:"A New Way of Looking at Heart Disease By Dr. Mercola",
		blogBody:"We have an epidemic of heart disease in this country and the conventional treatments, such as the use of statin drugs and surgeries involving artery bypasses and stents, typically do not work well. So, what does? Dr. Thomas Cowan is a family physician and a founding member of the Weston A. Price Foundation. In his book, \"Human Heart, Cosmic Heart: A Doctor's Quest to Understand, Treat, and Prevent Cardiovascular Disease,\" which is also available as an audiobook from Audible, he helps answer that question. It's a fascinating book, and not overly technical, making it an excellent addition to any layman's health library. \"Basically, the book has three parts,\" Cowan says. \"For whatever reason, my destiny in my career is that I take on some of the biggest accepted wisdoms … [and] I try to figure out whether they're actually true or not. The first part is my [personal] story … [In] the second part, I examine the theory that the heart is a pump. I say that the heart is not a pump. Then I explain why the blood moves and what the heart is doing, and the interesting ramifications of that. The third part is … [about] what causes heart attacks … Here is an interesting point: I learned in medical school there were four major coronary arteries. In some places, it says three. In some places, it says two. Even the basics of how many major coronary arteries we have is actually in dispute. It's a matter of semantics.\" Questioning the Role of Arterial Plaque in Heart Attacks Regardless of the exact number, conventional wisdom states that the coronary arteries, i.e., major blood vessels, supply all of the blood flow to the heart. If one or more of them gets blocked with plaque, a bottleneck forms that prevents blood from getting through.",
		date: Date()
	},
	{
		blogTitle:"Quercetin Protects Against Pesticides’ Damaging Effects By Michael Downey",
		blogBody:"While pesticides kill pests, they also pose danger to humans. Unprotected human exposure has been linked to cancer, endocrine complications, respiratory disorders, and organ failure. More worrisome are studies showing pesticide exposure can increase risk of neurodegenerative diseases. A number of studies, some published in 2016, indicate that the plant flavonoid quercetin can inhibit the damaging effects of pesticides. Pesticides are found in our food, air and water. Harmful chemicals are so abundant in our environment that we often absorb them without eating food. With advances in manufacturing, many pesticides are no longer sprayed on crops. Instead, systemic pesticides are mixed in with fertilizer and absorbed by plants through their vascular system. This makes it impossible for consumers to wash off pesticide residue because it’s within the fruits and vegetables that you eat. While everyone is vulnerable to the dangers of pesticides, those especially at risk include children, pregnant women, sick persons, and the elderly. Pesticide exposure can result in conditions ranging from learning disabilities to Parkinson’s disease and cancer.3-6 Because many different types of pesticides are used by farmers, exposure can overwhelm our efforts to stay healthy. Even everyday lawn chemicals pose risks and can remain in our body for decades. Quercetin, a flavonol occurring in certain fruits and vegetables,9-11 shows promise in animal studies to protect against some of the dangers of pesticides.12,13 Until farmers completely stop their use, we are always at risk. But initial studies in the laboratory show that quercetin can provide some measure of cellular protection.",
		date: Date()
	},
];
Blog.create(blogs,() => process.exit(0))
